# Generated by Django 4.2.3 on 2023-11-22 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracked_products',
            name='start_price_change_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tracked_products',
            name='start_tracking_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
