# Generated by Django 4.2.3 on 2023-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0004_alter_tracked_products_previous_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracked_products',
            name='previous_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracked_products',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
