# Generated by Django 4.2.3 on 2023-07-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_category_spirits_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumeitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumeitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spirits',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.category'),
        ),
    ]
