# Generated by Django 4.2.3 on 2023-07-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_volumeitem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spirits',
            new_name='Spirit',
        ),
    ]
