# Generated by Django 4.2.3 on 2023-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_rename_spirits_spirit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default='x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spirit',
            name='slug',
            field=models.SlugField(default='x'),
            preserve_default=False,
        ),
    ]
