# Generated by Django 4.2.3 on 2023-08-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_account_slug_spirit_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.category')),
            ],
        ),
        migrations.AlterField(
            model_name='volumeitem',
            name='spirit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.product'),
        ),
        migrations.DeleteModel(
            name='Spirit',
        ),
    ]
