# Generated by Django 4.2.3 on 2023-08-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_product_alter_volumeitem_spirit_delete_spirit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volumeitem',
            old_name='spirit',
            new_name='product',
        ),
    ]
