# Generated by Django 4.2.3 on 2023-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_rename_spirit_volumeitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_nr',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
